name = "hal_embedded"
description = "Hardware Abstraction Layer (HAL)"
version = "1.0.0"
licenses = "BSD-3-Clause"
tags = ["embedded"]

website = "https://github.com/ohenley/hal_embedded"

authors = ["AdaCore"]
maintainers = ["olivier henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[[depends-on]]
beta_types = "1.0.0"
